###############################################################
### Copyright©2024. Caris MPI, Inc. All rights reserved.###
###############################################################


pythonCmd: 'PATH TO PYTHON INTERPRETER'
sentiEnv : 'COMMAND TO EXPORT SENTIEON LICENSE SERVER IP AND PORT'
sentiPath : 'PATH TO SENTIEON BIN DIRECTORY'
threads: NUMBER_THREADS_FOR_SENTIEON
hg38_RefSeq_file : 'PATH TO HG38 .FA FILE'
gatk     : "PATH TO GATK DIRECTORY"
snpeff   : "PATH TO SNPEFF DIRECTORY"
# regions/targets
targets_padded : 'PATH TO THE BAIT BED'
cprvUniverse: 'PATH TO THE CPRV UNIVERSE CSV'

cnvkitReference : 'PATH TO THE CNVKIT REFERENCE CNN'
binMeta : 'PATH TO THE BIN PICKLE USED FOR MUTATIONOME AND COPYOME'
cbr_bed : 'PATH TO THE CONTIGUOUS BAITED REGIONS BED'
contamination_bed : 'PATH TO CONTAMINATED REGIONS BED'
smartbinmeta : 'PATH TO THE SMARTBIN POSITION CSV'
fragExclusionRegions : 'PATH TO EXCLUSION LIST OF REGIONS'
Common_CH : 'PATH TO COMMON CHIP VARIANTS CSV'
